'use client';

import PageContainer from '@/components/layout/page-container';
import { ArrowDownLeft, ArrowUpRight, Boxes, CheckCircle2, ChevronRight, Clock3, Download, Ellipsis, Filter, PackageCheck, PackageOpen, Plus, RefreshCw, SlidersHorizontal, Truck, Warehouse } from 'lucide-react';

const kpis = [
  { label: 'Inventory value', value: '$284,390', change: '+8.2%', detail: 'vs. last month', icon: Boxes, color: 'text-indigo-600 bg-indigo-50' },
  { label: 'Units in stock', value: '18,642', change: '+4.6%', detail: 'across 3 locations', icon: PackageCheck, color: 'text-teal-600 bg-teal-50' },
  { label: 'Low stock items', value: '24', change: 'Needs attention', detail: '8 critical items', icon: PackageOpen, color: 'text-amber-600 bg-amber-50' },
  { label: 'Open operations', value: '37', change: '12 due today', detail: 'receipts & deliveries', icon: Clock3, color: 'text-rose-600 bg-rose-50' },
];

const operations = [
  { ref: 'REC-1048', type: 'Receipt', partner: 'Apex Steel Supplies', location: 'Main Warehouse', status: 'Ready', qty: '+240 units', time: '12 min ago' },
  { ref: 'DEL-0821', type: 'Delivery', partner: 'Northstar Manufacturing', location: 'Production Floor', status: 'Picking', qty: '-84 units', time: '28 min ago' },
  { ref: 'TRF-0394', type: 'Transfer', partner: 'Main Warehouse → Rack B', location: 'Warehouse 01', status: 'Waiting', qty: '62 units', time: '1 hr ago' },
  { ref: 'ADJ-0117', type: 'Adjustment', partner: 'Cycle count correction', location: 'Spare Parts Room', status: 'Done', qty: '-12 units', time: '2 hrs ago' },
];

const locations = [
  { name: 'Main Warehouse', units: '12,480', capacity: 78, badge: 'WH-01', color: 'bg-indigo-500' },
  { name: 'Production Floor', units: '4,892', capacity: 54, badge: 'PR-02', color: 'bg-teal-500' },
  { name: 'Spare Parts Room', units: '1,270', capacity: 32, badge: 'SP-03', color: 'bg-violet-500' },
];

const statusStyles: Record<string, string> = {
  Ready: 'bg-emerald-50 text-emerald-700',
  Picking: 'bg-blue-50 text-blue-700',
  Waiting: 'bg-violet-50 text-violet-700',
  Done: 'bg-slate-100 text-slate-600',
};

function Status({ value }: { value: string }) {
  return <span className={'inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold ' + statusStyles[value]}><span className="size-1.5 rounded-full bg-current" />{value}</span>;
}

export default function OverViewPage() {
  return (
    <PageContainer>
      <div className="min-h-full bg-[#f7f8fc] px-4 py-6 dark:bg-slate-950 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-[1480px] space-y-6">
          <header className="flex flex-col justify-between gap-4 md:flex-row md:items-end">
            <div><div className="mb-2 flex items-center gap-2 text-xs font-medium text-slate-400"><span>Workspace</span><ChevronRight className="size-3" /><span className="text-indigo-500">Overview</span></div><h1 className="text-2xl font-bold tracking-[-0.03em] text-slate-950 dark:text-white sm:text-3xl">Good morning, Rithivkesh <span className="text-xl">✦</span></h1><p className="mt-1 text-sm text-slate-500">Here’s what’s happening across your inventory today.</p></div>
            <div className="flex flex-wrap items-center gap-2"><button className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3.5 text-sm font-medium text-slate-600 shadow-sm hover:border-slate-300 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300"><Download className="size-4" /> Export report</button><button className="inline-flex h-10 items-center gap-2 rounded-lg bg-indigo-600 px-4 text-sm font-semibold text-white shadow-sm shadow-indigo-200 hover:bg-indigo-700"><Plus className="size-4" /> New operation</button></div>
          </header>

          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(({ label, value, change, detail, icon: Icon, color }) => <div key={label} className="group rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_2px_10px_rgba(15,23,42,0.03)] transition hover:-translate-y-0.5 hover:shadow-lg dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between"><div className={'flex size-10 items-center justify-center rounded-xl ' + color}><Icon className="size-[18px]" /></div><Ellipsis className="size-4 text-slate-300 opacity-0 group-hover:opacity-100" /></div><p className="mt-4 text-sm font-medium text-slate-500">{label}</p><div className="mt-1 flex items-end justify-between gap-2"><p className="text-2xl font-bold tracking-tight text-slate-950 dark:text-white">{value}</p><span className="mb-1 text-[11px] font-semibold text-emerald-600">{change}</span></div><p className="mt-1 text-xs text-slate-400">{detail}</p></div>)}</div>

          <div className="grid gap-5 xl:grid-cols-[1.4fr_0.9fr]">
            <section className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-[0_2px_10px_rgba(15,23,42,0.03)] dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-3 border-b border-slate-100 px-5 py-5 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-slate-900 dark:text-white">Inventory activity</h2><p className="mt-1 text-xs text-slate-400">Recent movements and operational updates</p></div><div className="flex items-center gap-2"><button className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-300"><Filter className="size-3.5" /> Filter</button><button className="p-2 text-slate-400 hover:text-indigo-600"><RefreshCw className="size-4" /></button></div></div><div className="hidden grid-cols-[1.05fr_1.2fr_1.2fr_0.7fr_0.7fr] gap-4 border-b border-slate-100 bg-slate-50/70 px-5 py-3 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400 sm:grid"><span>Reference</span><span>Partner / activity</span><span>Location</span><span>Quantity</span><span>Status</span></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{operations.map((operation) => <div key={operation.ref} className="grid gap-3 px-5 py-4 transition hover:bg-slate-50/70 sm:grid-cols-[1.05fr_1.2fr_1.2fr_0.7fr_0.7fr] sm:items-center sm:gap-4"><div className="flex items-center gap-3"><div className="hidden size-8 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 sm:flex">{operation.type === 'Receipt' ? <ArrowDownLeft className="size-4" /> : operation.type === 'Delivery' ? <ArrowUpRight className="size-4" /> : operation.type === 'Transfer' ? <Truck className="size-4" /> : <SlidersHorizontal className="size-4" />}</div><div><p className="text-sm font-semibold text-slate-800 dark:text-slate-200">{operation.ref}</p><p className="text-xs text-slate-400 sm:hidden">{operation.type} · {operation.time}</p></div></div><div><p className="text-sm text-slate-700 dark:text-slate-300">{operation.partner}</p><p className="text-xs text-slate-400">{operation.type} · {operation.time}</p></div><p className="text-xs text-slate-500">{operation.location}</p><p className={'text-sm font-semibold ' + (operation.qty.startsWith('+') ? 'text-emerald-600' : operation.qty.startsWith('-') ? 'text-rose-500' : 'text-slate-700')}>{operation.qty}</p><Status value={operation.status} /></div>)}</div><button className="flex w-full items-center justify-center gap-1 border-t border-slate-100 py-3 text-xs font-semibold text-indigo-600 hover:bg-indigo-50/50">View all activity <ChevronRight className="size-3.5" /></button></section>

            <section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_2px_10px_rgba(15,23,42,0.03)] dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between"><div><h2 className="font-semibold text-slate-900 dark:text-white">Stock health</h2><p className="mt-1 text-xs text-slate-400">Across all locations</p></div><Ellipsis className="size-4 text-slate-400" /></div><div className="mt-7 flex items-center gap-6"><div className="relative flex size-32 shrink-0 items-center justify-center rounded-full" style={{ background: 'conic-gradient(#10b981 0 72%, #fbbf24 72% 90%, #fb7185 90% 100%)' }}><div className="flex size-24 flex-col items-center justify-center rounded-full bg-white dark:bg-slate-900"><span className="text-2xl font-bold text-slate-900 dark:text-white">72%</span><span className="text-[10px] text-slate-400">healthy</span></div></div><div className="w-full space-y-3">{[['Healthy stock','72','bg-emerald-500'],['Low stock','18','bg-amber-400'],['Out of stock','10','bg-rose-400']].map(([label, value, color]) => <div key={label} className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-slate-500"><span className={'size-2 rounded-full ' + color} />{label}</span><span className="font-semibold text-slate-700 dark:text-slate-300">{value}%</span></div>)}</div></div><div className="mt-7 rounded-xl border border-amber-100 bg-amber-50/70 p-3.5"><div className="flex gap-3"><PackageOpen className="mt-0.5 size-4 text-amber-600" /><div><p className="text-xs font-semibold text-amber-900">24 items need attention</p><p className="mt-1 text-[11px] leading-relaxed text-amber-700/80">Review reorder levels before the next receiving window.</p></div></div></div></section>
          </div>

          <div className="grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_2px_10px_rgba(15,23,42,0.03)] dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-slate-900 dark:text-white">Warehouse capacity</h2><p className="mt-1 text-xs text-slate-400">Current utilization by location</p></div><button className="text-xs font-semibold text-indigo-600 hover:text-indigo-700">Manage locations</button></div><div className="mt-5 grid gap-4 sm:grid-cols-3">{locations.map((location) => <div key={location.badge} className="rounded-xl border border-slate-100 p-3.5 dark:border-slate-800"><div className="flex items-center justify-between"><div className="flex size-8 items-center justify-center rounded-lg bg-slate-50 text-slate-500 dark:bg-slate-800 dark:text-slate-300"><Warehouse className="size-4" /></div><span className="text-[10px] font-bold tracking-wider text-slate-400">{location.badge}</span></div><p className="mt-3 truncate text-xs font-semibold text-slate-700 dark:text-slate-300">{location.name}</p><div className="mt-3 flex items-center justify-between text-[11px]"><span className="text-slate-400">{location.units} units</span><span className="font-semibold text-slate-600 dark:text-slate-300">{location.capacity}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={'h-full rounded-full ' + location.color} style={{ width: location.capacity + '%' }} /></div></div>)}</div></section><section className="rounded-2xl bg-slate-950 p-5 text-white shadow-[0_10px_25px_rgba(15,23,42,0.16)]"><div className="flex items-start justify-between"><div><span className="inline-flex items-center gap-1.5 rounded-full bg-white/10 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-indigo-200"><CheckCircle2 className="size-3" /> System status</span><h2 className="mt-4 text-lg font-semibold">Everything is in sync</h2><p className="mt-1 text-xs leading-relaxed text-slate-400">Your stock ledger was last reconciled 4 minutes ago.</p></div><div className="flex size-10 items-center justify-center rounded-xl bg-emerald-400/15 text-emerald-300"><CheckCircle2 className="size-5" /></div></div><div className="mt-6 grid grid-cols-2 gap-3 border-t border-white/10 pt-4"><div><p className="text-[10px] uppercase tracking-wider text-slate-500">Last sync</p><p className="mt-1 text-sm font-semibold">Today, 09:42 AM</p></div><div><p className="text-[10px] uppercase tracking-wider text-slate-500">API uptime</p><p className="mt-1 text-sm font-semibold">99.98%</p></div></div></section></div>
        </div>
      </div>
    </PageContainer>
  );
}
